language: java

dist: trusty

jdk:

- oraclejdk8

sudo: false

script:
before_install:
  - pip install --user codecov

- mvn test

- mvn evosuite:info


after_success:
  - codecov --file coverage/lcov.info --disable search
